sum="Bamboozled"
print(sum[ -2])
print(sum[2:])
print(sum[2:-1])
print(sum[:6])
print(sum[-8:])
print(sum[0:6])
print(sum[2:10])
print(sum[:-4])
print(sum[:2])
 
s="Bring It On"
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.swapcase())
print(s.replace("It","Him"))

s = "Humpty Dumpty"
print(s)
print(s.isalpha())
print(s.isdigit())
print(s.isalnum())
print(s.islower())
print(s.startswith("Hum"))
print(s.endswith("dum"))

msg="Keep yourself warm"
print(msg.partition(" "))
print(msg.split())
print(msg.swapcase())
print(msg.count("e"))
print(len(msg))
print(msg[-1])
print(msg[1:1:1])
print(msg[-1:3])
print(msg[:-3])
print(msg[-3:])
print(msg[:-2])
